version: '3'
services:
  egen-postgres:
      image: "postgres:9.6-alpine"
      container_name: egen-postgres
      volumes:
        - egen-data:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=egenorders
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2191:2181 
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "batchOrders"
volumes:
  egen-data: