eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
#logging:
#  file: /Users/gouthamkrs/Desktop/micro.log
 
 
spring:
#  zipkin:
#    base-url: http://localhost:9411/
  cloud:
    stream:
      bindings:
        output:
          destination: batchOrders 
#spring:
#  zipkin:
#    base-url: http://localhost:9411/

  kafka:
    consumer:
      fetch-max-wait: 1000
      
        